### ISSUE TITLE
Should probably document that setting properties on a primitive in strict mode throws in Firefox 46 and later

### ISSUE THREAD

**Issue by bzbarsky** [fxsitecompat/www.fxsitecompat.com#11]
Testcase:

```
(function() {
   "use strict";
   false.b="";
})();
```

This is a no-op in Firefox 45, throws in Firefox 46 and later (and should throw per ES spec, afaict).

**Comment by kyoshino** [comment]
Thanks for flagging! Which bug is this?

**Comment by kyoshino** [comment]
Ah maybe [Bug 603201](https://bugzilla.mozilla.org/show_bug.cgi?id=603201) + [Bug 1240792](https://bugzilla.mozilla.org/show_bug.cgi?id=1240792). Will prepare the doc today.

**Comment by bzbarsky** [comment]
Yes, that's it.  Sorry, there's a mail I sent _after_ filing this that you're cced on that has the link to the bug... ;)

**Comment by kyoshino** [comment]
Got your mail. Thanks :smiley_cat:

**Comment by kyoshino** [comment]
Posted the [document](https://www.fxsitecompat.com/en-CA/docs/2016/setting-properties-on-a-primitive-now-throws-in-strict-mode/)!
