### ISSUE TITLE
English copyediting

### ISSUE THREAD

**Issue by cvrebert** [fxsitecompat/www.fxsitecompat.com#14]
In https://github.com/fxsitecompat/www.fxsitecompat.com/blob/master/content/en-CA/docs/2016/retuning-non-object-value-by-iterator-next-will-throw.md
"retuning" [sic] should be "returning",
and "by" should be "from".

**Comment by kyoshino** [comment]
Thank you @cvrebert! Somehow my spellchecker ignored the typo. Fixed!
