### ISSUE TITLE
Recommend local web server for Android

### ISSUE THREAD

**Issue by pinobatch** [fxsitecompat/www.fxsitecompat.com#15]
From "[Local files are now each given a different origin](https://www.fxsitecompat.dev/en-CA/docs/2019/local-files-are-now-each-given-a-different-origin/)":
> While a simple, self-contained HTML file may still work, it’s highly recommended to set up a local server if you want to test a site with assets. There are easy-to-use tools like MAMP or XAMPP, and macOS also comes with the Apache server.

MAMP is for Windows; XAMPP is for Windows, macOS, and GNU/Linux; and the version of Apache HTTP Server bundled with some versions of macOS is for macOS. This covers three out of the four platforms supported by Firefox with its own rendering engine, the fourth being Android. The anticipated use case is someone who does "Save As > Web Page, complete" and then copies the resulting .html file and its supporting files to an Android device for later offline viewing in Firefox for Android. (An offline Android device may be a tablet, a phone on a voice-only plan, or a phone whose data transfer allowance has been used up for the month.) Which local web server for Android should this document recommend?

**Comment by kyoshino** [comment]
Hi @pinobatch, thanks for your comment! When I test a website locally, I simply run the site on the Apache server on my MacBook Pro, and access it from browsers on mobile or tablet using the machine’s IP address (192.168.0.x). I think the same can be done with MAMP/XAMPP; just need to know your IP address, connect to the same LAN, and configure the firewall if needed.

This technique is not specific to Firefox/Gecko, of course. You can use any browser on an Android phone/tablet or iPad/iPhone.

Looks like it’s possible to [run a web server on Android](https://www.google.com/search?q=web+server+Android) but I have never tried it personally.

If end users, not developers, want to keep a copy of web page for later use, it’s probably better to take a screenshot of it. FYI, Mozilla offers [Firefox ScreenshotGo](https://play.google.com/store/apps/details?id=org.mozilla.screenshot.go) and [Pocket](https://getpocket.com/) for offline browsing.

**Comment by pinobatch** [comment]
When you access 192.168.0.x through HTTP to your MacBook Pro, how do you work around these limits?

1. You have to be on the same network as your MBP. Even if you are at a public Wi-Fi hotspot or subscribe to cellular Internet, 192.168.0.x on that network isn't the same as 192.168.0.x on your home network.
2. You cannot do anything for which web browsers require a [secure context](https://pineight.com/mw/index.php?title=Secure_Contexts). The `https` scheme is considered secure, but the only `http` origin considered secure by browsers is `http://localhost`.

The example that motivated this issue was a browser-based single-player video game that needs to load subresources through XHR or similar. A screenshot of a video game is no substitute for the game itself. And even if it were a text document, as opposed to a game, the user cannot copy text from a screenshot and paste it elsewhere as editable text.
