### ISSUE TITLE
SSL Report

### ISSUE THREAD

**Issue by yfdyh000** [fxsitecompat/www.fxsitecompat.com#4]
https://www.ssllabs.com/ssltest/analyze.html?d=fxsitecompat.com

This server is vulnerable to the POODLE attack. If possible, disable SSL 3 to mitigate. Grade capped to C.   MORE INFO »
This server accepts the RC4 cipher, which is weak. Grade capped to B.  MORE INFO »
The server does not support Forward Secrecy with the reference browsers.  MORE INFO » 

Not really risk, but not so beautiful. In addition, HTTP/2.0 and br (brotli) also can be considered, even if it is the future.

**Comment by kyoshino** [comment]
Thanks @yfdyh000 for your report, I'll check the server config today.

**Comment by kyoshino** [comment]
Disabled SSLv3 and RC4 but the rating is still B :confused: 

``` aconf
SSLProtocol All -SSLv2 -SSLv3
SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5:!RC4
```

**Comment by kyoshino** [comment]
Looks like I had to edit `/etc/apache2/mods-enabled/ssl.conf` instead of `/etc/apache2/sites-enabled/fxsitecompat.com.conf`. Now getting A+ by following [this example](https://community.qualys.com/blogs/securitylabs/2013/08/05/configuring-apache-nginx-and-openssl-for-forward-secrecy) :tada:

**Comment by kyoshino** [comment]
Upgraded to HTTP/2 today.
