### ISSUE TITLE
banner background image

### ISSUE THREAD

**Issue by jbshirk** [fxsitecompat/www.fxsitecompat.com#9]
Hi, this is a great hugo site, the only one that supports multiple languages that I have been able to work with without breaking it. Thank you!

This isn't an issue per se, I just have been unable to determine where exactly I can change the banner background image so I thought best to ask here.

**Comment by kyoshino** [comment]
The background image is specified in [`[role="banner"]::after`](https://github.com/fxsitecompat/www.fxsitecompat.com/blob/master/static/styles/base.css#L243).

By the way, this site is not intended to be used as a Hugo theme. You can refer to the templates for your own projects, but the design should not be copied. You may want to visit [themes.gohugo.io](http://themes.gohugo.io/) for great themes that can be used freely. Thanks!
